import "./global.css"
import Footer from "./layoutcomponents/Footer/Footer";
import NavBar from "./layoutcomponents/navbar/NavBar";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className="home">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
